name: rust_book
description: Demonstrates how to use the flutter_inappwebview plugin.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_downloader: 1.10.2
  path_provider: 2.0.15
  permission_handler: 10.2.0
  url_launcher: 6.1.11
  pointer_interceptor: ^0.9.3+4
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # integration_test: ^1.0.2+1
#  integration_test:
#    git:
#      url: https://github.com/flutter/plugins.git
#      path: packages/integration_test
  flutter_lints: ^2.0.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/book/iterators.html
    - assets/book/lifetimes.html
    - assets/book/ch16-04-extensible-concurrency-sync-and-send.html
    - assets/book/ch09-02-recoverable-errors-with-result.html
    - assets/book/concurrency.html
    - assets/book/ch06-00-enums.html
    - assets/book/patterns.html
    - assets/book/ch17-01-what-is-oo.html
    - assets/book/ch11-01-writing-tests.html
    - assets/book/loops.html
    - assets/book/operators-and-overloading.html
    - assets/book/conditional-compilation.html
    - assets/book/unsafe.html
    - assets/book/elasticlunr.min.js
    - assets/book/type-aliases.html
    - assets/book/ch13-01-closures.html
    - assets/book/ch04-01-what-is-ownership.html
    - assets/book/raw-pointers.html
    - assets/book/appendix-06-translation.html
    - assets/book/effective-rust.html
    - assets/book/clipboard.min.js
    - assets/book/choosing-your-guarantees.html
    - assets/book/ch05-00-structs.html
    - assets/book/ch19-06-macros.html
    - assets/book/unsized-types.html
    - assets/book/ch02-00-guessing-game-tutorial.html
    - assets/book/ch07-01-packages-and-crates.html
    - assets/book/casting-between-types.html
    - assets/book/ch08-00-common-collections.html
    - assets/book/macros.html
    - assets/book/strings.html
    - assets/book/ch06-02-match.html
    - assets/book/appendix-03-derivable-traits.html
    - assets/book/ch12-04-testing-the-librarys-functionality.html
    - assets/book/method-syntax.html
    - assets/book/ch12-01-accepting-command-line-arguments.html
    - assets/book/enums.html
    - assets/book/drop.html
    - assets/book/ch20-00-final-project-a-web-server.html
    - assets/book/ch13-03-improving-our-io-project.html
    - assets/book/structs.html
    - assets/book/ch20-02-multithreaded.html
    - assets/book/ch10-00-generics.html
    - assets/book/ch03-01-variables-and-mutability.html
    - assets/book/ch01-02-hello-world.html
    - assets/book/ch09-01-unrecoverable-errors-with-panic.html
    - assets/book/attributes.html
    - assets/book/ch19-03-advanced-traits.html
    - assets/book/crates-and-modules.html
    - assets/book/trait-objects.html
    - assets/book/ch07-02-defining-modules-to-control-scope-and-privacy.html
    - assets/book/SUMMARY.html
    - assets/book/appendix-07-nightly-rust.html
    - assets/book/closures.html
    - assets/book/using-rust-without-the-standard-library.html
    - assets/book/ufcs.html
    - assets/book/ch03-00-common-programming-concepts.html
    - assets/book/ch09-00-error-handling.html
    - assets/book/ch19-01-unsafe-rust.html
    - assets/book/associated-types.html
    - assets/book/highlight.js
    - assets/book/ch16-03-shared-state.html
    - assets/book/tomorrow-night.css
    - assets/book/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.html
    - assets/book/if.html
    - assets/book/ch12-03-improving-error-handling-and-modularity.html
    - assets/book/traits.html
    - assets/book/ch12-02-reading-a-file.html
    - assets/book/glossary.html
    - assets/book/ch17-03-oo-design-patterns.html
    - assets/book/getting-started.html
    - assets/book/borrow-and-asref.html
    - assets/book/ch18-01-all-the-places-for-patterns.html
    - assets/book/ferris.css
    - assets/book/syntax-index.html
    - assets/book/appendix-01-keywords.html
    - assets/book/const-and-static.html
    - assets/book/mark.min.js
    - assets/book/ch10-03-lifetime-syntax.html
    - assets/book/ch14-02-publishing-to-crates-io.html
    - assets/book/syntax-and-semantics.html
    - assets/book/ch14-00-more-about-cargo.html
    - assets/book/ch16-01-threads.html
    - assets/book/ch06-01-defining-an-enum.html
    - assets/book/ch19-04-advanced-types.html
    - assets/book/ch10-02-traits.html
    - assets/book/primitive-types.html
    - assets/book/ch07-05-separating-modules-into-different-files.html
    - assets/book/deref-coercions.html
    - assets/book/ch19-05-advanced-functions-and-closures.html
    - assets/book/if-let.html
    - assets/book/guessing-game.html
    - assets/book/.nojekyll
    - assets/book/variable-bindings.html
    - assets/book/ch17-00-oop.html
    - assets/book/documentation.html
    - assets/book/ch01-00-getting-started.html
    - assets/book/ch14-03-cargo-workspaces.html
    - assets/book/ch17-02-trait-objects.html
    - assets/book/ch12-00-an-io-project.html
    - assets/book/index.html
    - assets/book/error-handling.html
    - assets/book/ch15-00-smart-pointers.html
    - assets/book/ch18-02-refutability.html
    - assets/book/ferris.js
    - assets/book/ch08-03-hash-maps.html
    - assets/book/ch11-00-testing.html
    - assets/book/ch06-03-if-let.html
    - assets/book/ch14-05-extending-cargo.html
    - assets/book/release-channels.html
    - assets/book/mutability.html
    - assets/book/procedural-macros.html
    - assets/book/ch11-03-test-organization.html
    - assets/book/ch05-03-method-syntax.html
    - assets/book/ch09-03-to-panic-or-not-to-panic.html
    - assets/book/appendix-02-operators.html
    - assets/book/ch05-02-example-structs.html
    - assets/book/ch14-01-release-profiles.html
    - assets/book/ch03-02-data-types.html
    - assets/book/ch00-00-introduction.html
    - assets/book/title-page.html
    - assets/book/ch13-04-performance.html
    - assets/book/ch13-00-functional-features.html
    - assets/book/ch03-03-how-functions-work.html
    - assets/book/highlight.css
    - assets/book/match.html
    - assets/book/ch15-02-deref.html
    - assets/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html
    - assets/book/ch15-05-interior-mutability.html
    - assets/book/ch04-03-slices.html
    - assets/book/ch05-01-defining-structs.html
    - assets/book/README.html
    - assets/book/references-and-borrowing.html
    - assets/book/ch14-04-installing-binaries.html
    - assets/book/ch08-01-vectors.html
    - assets/book/ch19-00-advanced-features.html
    - assets/book/ch04-02-references-and-borrowing.html
    - assets/book/ch20-01-single-threaded.html
    - assets/book/ch20-03-graceful-shutdown-and-cleanup.html
    - assets/book/ch16-00-concurrency.html
    - assets/book/ayu-highlight.css
    - assets/book/foreword.html
    - assets/book/appendix-05-editions.html
    - assets/book/ch13-02-iterators.html
    - assets/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html
    - assets/book/book.js
    - assets/book/favicon.svg
    - assets/book/ch18-03-pattern-syntax.html
    - assets/book/ch03-04-comments.html
    - assets/book/ch18-00-patterns.html
    - assets/book/ch08-02-strings.html
    - assets/book/compiler-plugins.html
    - assets/book/ch15-03-drop.html
    - assets/book/vectors.html
    - assets/book/searcher.js
    - assets/book/ch01-03-hello-cargo.html
    - assets/book/searchindex.json
    - assets/book/searchindex.js
    - assets/book/favicon.png
    - assets/book/testing.html
    - assets/book/ch01-01-installation.html
    - assets/book/ch15-01-box.html
    - assets/book/appendix-00.html
    - assets/book/generics.html
    - assets/book/ch15-04-rc.html
    - assets/book/ownership.html
    - assets/book/ch12-06-writing-to-stderr-instead-of-stdout.html
    - assets/book/functions.html
    - assets/book/ch12-05-working-with-environment-variables.html
    - assets/book/print.html
    - assets/book/ch15-06-reference-cycles.html
    - assets/book/ch11-02-running-tests.html
    - assets/book/ch10-01-syntax.html
    - assets/book/ffi.html
    - assets/book/ch16-02-message-passing.html
    - assets/book/ch03-05-control-flow.html
    - assets/book/ch04-00-understanding-ownership.html
    - assets/book/bibliography.html
    - assets/book/the-stack-and-the-heap.html
    - assets/book/appendix-04-useful-development-tools.html
    - assets/book/css/general.css
    - assets/book/css/variables.css
    - assets/book/css/print.css
    - assets/book/css/chrome.css
    - assets/book/FontAwesome/css/font-awesome.css
    - assets/book/FontAwesome/fonts/FontAwesome.ttf
    - assets/book/FontAwesome/fonts/fontawesome-webfont.woff
    - assets/book/FontAwesome/fonts/fontawesome-webfont.woff2
    - assets/book/FontAwesome/fonts/fontawesome-webfont.svg
    - assets/book/FontAwesome/fonts/fontawesome-webfont.ttf
    - assets/book/FontAwesome/fonts/fontawesome-webfont.eot
    - assets/book/fonts/open-sans-v17-all-charsets-300.woff2
    - assets/book/fonts/source-code-pro-v11-all-charsets-500.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-800.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-600italic.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-300italic.woff2
    - assets/book/fonts/SOURCE-CODE-PRO-LICENSE.txt
    - assets/book/fonts/open-sans-v17-all-charsets-italic.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-800italic.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-600.woff2
    - assets/book/fonts/OPEN-SANS-LICENSE.txt
    - assets/book/fonts/fonts.css
    - assets/book/fonts/open-sans-v17-all-charsets-regular.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-700italic.woff2
    - assets/book/fonts/open-sans-v17-all-charsets-700.woff2
    - assets/book/img/trpl04-01.svg
    - assets/book/img/trpl04-03.svg
    - assets/book/img/trpl04-06.svg
    - assets/book/img/trpl20-01.png
    - assets/book/img/trpl14-01.png
    - assets/book/img/trpl15-01.svg
    - assets/book/img/trpl14-03.png
    - assets/book/img/trpl14-04.png
    - assets/book/img/trpl14-02.png
    - assets/book/img/trpl04-04.svg
    - assets/book/img/trpl15-04.svg
    - assets/book/img/trpl04-02.svg
    - assets/book/img/trpl04-05.svg
    - assets/book/img/trpl15-02.svg
    - assets/book/img/trpl15-03.svg
    - assets/book/img/ferris/panics.svg
    - assets/book/img/ferris/does_not_compile.svg
    - assets/book/img/ferris/not_desired_behavior.svg
    - assets/book/theme/2018-edition.css


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
